/** Playlists de catálogo para el Inicio (IDs fijos). */
export const playlistsCatalogoSeed = [
  // Vuelve a tu música
  {
    id: "catalog-forever-tu-gantel",
    nombre: "FOREVER TU GANTEL",
    descripcion: "Con Omar Courtz, Yan Block y más",
    seccion: "vuelve",
    color: "#3d5a80",
    creador: "NiB Music",
  },
  {
    id: "catalog-ferxxo",
    nombre: "FERXXO",
    descripcion: "Si sabe Ferxxo — Feid, Blessd y más",
    seccion: "vuelve",
    color: "#a8e000",
    creador: "NiB Music",
  },
  {
    id: "catalog-las-mas-bonitas",
    nombre: "Las más bonitas",
    descripcion: "Anuel AA y lo mejor del genre",
    seccion: "vuelve",
    color: "#c1121f",
    creador: "NiB Music",
  },
  {
    id: "catalog-karol-g",
    nombre: "KAROL G",
    descripcion: "Éxitos de Karol G",
    seccion: "vuelve",
    color: "#ff4d6d",
    creador: "NiB Music",
  },
  {
    id: "catalog-exitos-argentina",
    nombre: "Éxitos Argentina",
    descripcion: "Lo más escuchado en Argentina",
    seccion: "vuelve",
    color: "#74c69d",
    creador: "NiB Music",
  },
  {
    id: "catalog-noche-urbana",
    nombre: "Noche urbana",
    descripcion: "Reggaetón y vibes de madrugada",
    seccion: "vuelve",
    color: "#5a189a",
    creador: "NiB Music",
  },

  // Hecho para vos
  {
    id: "catalog-mix-diario-1",
    nombre: "Mix diario 1",
    descripcion: "Tu mezcla personalizada del día",
    seccion: "hecho",
    color: "#4361ee",
    creador: "NiB Music",
  },
  {
    id: "catalog-mix-diario-2",
    nombre: "Mix diario 2",
    descripcion: "Más descubrimientos para vos",
    seccion: "hecho",
    color: "#f72585",
    creador: "NiB Music",
  },
  {
    id: "catalog-mix-diario-3",
    nombre: "Mix diario 3",
    descripcion: "Canciones que te pueden gustar",
    seccion: "hecho",
    color: "#4cc9f0",
    creador: "NiB Music",
  },
  {
    id: "catalog-on-repeat",
    nombre: "On Repeat",
    descripcion: "Las que no paramos de escuchar",
    seccion: "hecho",
    color: "#ffd60a",
    creador: "NiB Music",
  },
  {
    id: "catalog-radar",
    nombre: "Release Radar",
    descripcion: "Novedades de artistas que seguís",
    seccion: "hecho",
    color: "#2ec4b6",
    creador: "NiB Music",
  },
  {
    id: "catalog-time-capsule",
    nombre: "Time Capsule",
    descripcion: "Un viaje por tu historial musical",
    seccion: "hecho",
    color: "#e76f51",
    creador: "NiB Music",
  },

  // Recientes (Tus me gusta se suma en Inicio desde el usuario)
  {
    id: "catalog-por-si-manana",
    nombre: "POR SI MAÑANA NO ESTOY",
    descripcion: "Playlist reciente",
    seccion: "recientes",
    color: "#6c757d",
    creador: "NiB Music",
  },
  {
    id: "catalog-radio-zizi",
    nombre: "Radio de ZIZI",
    descripcion: "Basada en ZIZI",
    seccion: "recientes",
    color: "#adb5bd",
    creador: "NiB Music",
  },
  {
    id: "catalog-5202",
    nombre: "5202",
    descripcion: "Selección reciente",
    seccion: "recientes",
    color: "#212529",
    creador: "NiB Music",
  },
  {
    id: "catalog-radio-vlone",
    nombre: "Radio de VLONE",
    descripcion: "Basada en VLONE",
    seccion: "recientes",
    color: "#343a40",
    creador: "NiB Music",
  },
  {
    id: "catalog-duki-reguetonero",
    nombre: "duki reguetonero",
    descripcion: "Duki en modo reggaetón",
    seccion: "recientes",
    color: "#7b2cbf",
    creador: "NiB Music",
  },
  {
    id: "catalog-duki-old",
    nombre: "Duki old",
    descripcion: "Clásicos de Duki",
    seccion: "recientes",
    color: "#9d4edd",
    creador: "NiB Music",
  },

  // Similares a Bad Bunny
  {
    id: "catalog-this-is-bad-bunny",
    nombre: "This Is Bad Bunny",
    descripcion: "Los esenciales de Bad Bunny",
    seccion: "similares",
    color: "#e9c46a",
    creador: "NiB Music",
  },
  {
    id: "catalog-radio-bad-bunny",
    nombre: "Radio Bad Bunny",
    descripcion: "Con Bad Bunny, Feid, Rauw Alejandro...",
    seccion: "similares",
    color: "#f4a261",
    creador: "NiB Music",
  },
  {
    id: "catalog-un-verano",
    nombre: "Un verano sin ti vibes",
    descripcion: "Inspirado en Un Verano Sin Ti",
    seccion: "similares",
    color: "#2a9d8f",
    creador: "NiB Music",
  },
  {
    id: "catalog-yhlqmdlg",
    nombre: "YHLQMDLG energy",
    descripcion: "Trap y perreo al estilo Bad Bunny",
    seccion: "similares",
    color: "#e76f51",
    creador: "NiB Music",
  },
  {
    id: "catalog-latino-hits",
    nombre: "Latino Hits",
    descripcion: "Los hits latinos del momento",
    seccion: "similares",
    color: "#264653",
    creador: "NiB Music",
  },
  {
    id: "catalog-trap-latino",
    nombre: "Trap latino",
    descripcion: "Lo mejor del trap en español",
    seccion: "similares",
    color: "#1d3557",
    creador: "NiB Music",
  },
  {
    id: "catalog-perreo-intenso",
    nombre: "Perreo intenso",
    descripcion: "Para la pista toda la noche",
    seccion: "similares",
    color: "#d62828",
    creador: "NiB Music",
  },
];
