/** Playlists de catálogo para el Inicio (IDs fijos). */
export const playlistsCatalogoSeed = [
  {
    id: "catalog-forever-tu-gantel",
    nombre: "FOREVER TU GANTEL",
    descripcion: "Con Omar Courtz, Yan Block y más",
    seccion: "vuelve",
    color: "#3d5a80",
    creador: "NiB Music",
    artistas: ["Omar Courtz", "Bryant Myers", "Arcangel", "Myke Towers", "Jhayco"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-ferxxo",
    nombre: "FERXXO",
    descripcion: "Si sabe Ferxxo — Feid, Blessd y más",
    seccion: "vuelve",
    color: "#a8e000",
    creador: "NiB Music",
    artistas: ["Feid", "Blessd", "Yandel", "Mora"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-las-mas-bonitas",
    nombre: "Las más bonitas",
    descripcion: "Anuel AA y lo mejor del genre",
    seccion: "vuelve",
    color: "#c1121f",
    creador: "NiB Music",
    artistas: ["Anuel AA", "Natti Natasha", "Becky G"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-karol-g",
    nombre: "KAROL G",
    descripcion: "Éxitos de Karol G",
    seccion: "vuelve",
    color: "#ff4d6d",
    creador: "NiB Music",
    artistas: ["KAROL G", "Karol G"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-exitos-argentina",
    nombre: "Éxitos Argentina",
    descripcion: "Lo más escuchado en Argentina",
    seccion: "vuelve",
    color: "#74c69d",
    creador: "NiB Music",
    artistas: ["DUKI", "Duki", "Maria Becerra", "LIT killah", "Nicki Nicole", "TINI", "Bizarrap", "Milo j"],
    generos: ["Trap", "Pop Latino"],
  },
  {
    id: "catalog-noche-urbana",
    nombre: "Noche urbana",
    descripcion: "Reggaetón y vibes de madrugada",
    seccion: "vuelve",
    color: "#5a189a",
    creador: "NiB Music",
    artistas: ["Rauw Alejandro", "Ozuna", "Sech", "Lunay", "Jay Wheeler", "Justin Quiles"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-mix-diario-1",
    nombre: "Mix diario 1",
    descripcion: "Tu mezcla personalizada del día",
    seccion: "hecho",
    color: "#4361ee",
    creador: "NiB Music",
    artistas: ["Bad Bunny", "Feid", "KAROL G", "Rauw Alejandro"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-mix-diario-2",
    nombre: "Mix diario 2",
    descripcion: "Más descubrimientos para vos",
    seccion: "hecho",
    color: "#f72585",
    creador: "NiB Music",
    artistas: ["DUKI", "Quevedo", "Mora", "Cris MJ"],
    generos: ["Trap", "Reggaeton"],
  },
  {
    id: "catalog-mix-diario-3",
    nombre: "Mix diario 3",
    descripcion: "Canciones que te pueden gustar",
    seccion: "hecho",
    color: "#4cc9f0",
    creador: "NiB Music",
    artistas: ["J Balvin", "Maluma", "Myke Towers", "Eladio Carrion"],
    generos: ["Reggaeton", "Trap"],
  },
  {
    id: "catalog-on-repeat",
    nombre: "On Repeat",
    descripcion: "Las que no paramos de escuchar",
    seccion: "hecho",
    color: "#ffd60a",
    creador: "NiB Music",
    artistas: ["Manuel Turizo", "Shakira", "ROSALÍA", "Grupo Frontera", "Peso Pluma"],
    generos: ["Pop Latino", "Latino"],
  },
  {
    id: "catalog-radar",
    nombre: "Release Radar",
    descripcion: "Novedades de artistas que seguís",
    seccion: "hecho",
    color: "#2ec4b6",
    creador: "NiB Music",
    artistas: ["Feid", "Bad Bunny", "Quevedo", "Saiko", "Milo j"],
    generos: ["Reggaeton", "Trap"],
  },
  {
    id: "catalog-time-capsule",
    nombre: "Time Capsule",
    descripcion: "Un viaje por tu historial musical",
    seccion: "hecho",
    color: "#e76f51",
    creador: "NiB Music",
    artistas: ["Daddy Yankee", "Don Omar", "Wisin", "Nicky Jam", "Ricky Martin", "Enrique Iglesias"],
    generos: ["Reggaeton", "Pop Latino"],
  },
  {
    id: "catalog-por-si-manana",
    nombre: "POR SI MAÑANA NO ESTOY",
    descripcion: "Playlist reciente",
    seccion: "recientes",
    color: "#6c757d",
    creador: "NiB Music",
    artistas: ["Bad Bunny", "Feid", "Mora"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-radio-zizi",
    nombre: "Radio de ZIZI",
    descripcion: "Basada en ZIZI",
    seccion: "recientes",
    color: "#adb5bd",
    creador: "NiB Music",
    artistas: ["Rauw Alejandro", "Jhayco", "Arcangel"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-5202",
    nombre: "5202",
    descripcion: "Selección reciente",
    seccion: "recientes",
    color: "#212529",
    creador: "NiB Music",
    artistas: ["Tainy", "Bad Bunny", "J Balvin"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-radio-vlone",
    nombre: "Radio de VLONE",
    descripcion: "Basada en VLONE",
    seccion: "recientes",
    color: "#343a40",
    creador: "NiB Music",
    artistas: ["Eladio Carrion", "DUKI", "Myke Towers"],
    generos: ["Trap", "Reggaeton"],
  },
  {
    id: "catalog-duki-reguetonero",
    nombre: "duki reguetonero",
    descripcion: "Duki en modo reggaetón",
    seccion: "recientes",
    color: "#7b2cbf",
    creador: "NiB Music",
    artistas: ["DUKI", "Duki", "Bizarrap", "LIT killah"],
    generos: ["Trap"],
  },
  {
    id: "catalog-duki-old",
    nombre: "Duki old",
    descripcion: "Clásicos de Duki",
    seccion: "recientes",
    color: "#9d4edd",
    creador: "NiB Music",
    artistas: ["DUKI", "Duki"],
    generos: ["Trap"],
  },
  {
    id: "catalog-this-is-bad-bunny",
    nombre: "This Is Bad Bunny",
    descripcion: "Los esenciales de Bad Bunny",
    seccion: "similares",
    color: "#e9c46a",
    creador: "NiB Music",
    artistas: ["Bad Bunny"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-radio-bad-bunny",
    nombre: "Radio Bad Bunny",
    descripcion: "Con Bad Bunny, Feid, Rauw Alejandro...",
    seccion: "similares",
    color: "#f4a261",
    creador: "NiB Music",
    artistas: ["Bad Bunny", "Feid", "Rauw Alejandro", "J Balvin"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-un-verano",
    nombre: "Un verano sin ti vibes",
    descripcion: "Inspirado en Un Verano Sin Ti",
    seccion: "similares",
    color: "#2a9d8f",
    creador: "NiB Music",
    artistas: ["Bad Bunny"],
    generos: ["Reggaeton"],
  },
  {
    id: "catalog-yhlqmdlg",
    nombre: "YHLQMDLG energy",
    descripcion: "Trap y perreo al estilo Bad Bunny",
    seccion: "similares",
    color: "#e76f51",
    creador: "NiB Music",
    artistas: ["Bad Bunny", "Jhayco", "Anuel AA"],
    generos: ["Reggaeton", "Trap"],
  },
  {
    id: "catalog-latino-hits",
    nombre: "Latino Hits",
    descripcion: "Los hits latinos del momento",
    seccion: "similares",
    color: "#264653",
    creador: "NiB Music",
    artistas: ["Shakira", "Manuel Turizo", "Maluma", "Grupo Frontera", "Peso Pluma", "ROSALÍA"],
    generos: ["Pop Latino", "Latino"],
  },
  {
    id: "catalog-trap-latino",
    nombre: "Trap latino",
    descripcion: "Lo mejor del trap en español",
    seccion: "similares",
    color: "#1d3557",
    creador: "NiB Music",
    artistas: ["DUKI", "Quevedo", "Eladio Carrion", "Bizarrap", "Milo j"],
    generos: ["Trap"],
  },
  {
    id: "catalog-perreo-intenso",
    nombre: "Perreo intenso",
    descripcion: "Para la pista toda la noche",
    seccion: "similares",
    color: "#d62828",
    creador: "NiB Music",
    artistas: ["Daddy Yankee", "Farruko", "Don Omar", "Nicky Jam", "Nio Garcia", "Lenny Tavarez"],
    generos: ["Reggaeton"],
  },
];
